//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortuga_Dobrodiy_3isp11_16.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductSale()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int IDProductSale { get; set; }
        public System.DateTime SaleDate { get; set; }
        public byte TableNum { get; set; }
        public int IDPayment { get; set; }
        public System.DateTime ReadyTime { get; set; }
        public string ClientName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
