//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortuga_Dobrodiy_3isp11_16.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTag
    {
        public int IDProductTag { get; set; }
        public int IDProduct { get; set; }
        public int IDTag { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
