//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortuga_Dobrodiy_3isp11_16.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_pss
    {
        public string ClientName { get; set; }
        public int TableNumber { get; set; }
        public string Payment { get; set; }
        public System.DateTime dateTime { get; set; }
        public int IDProductSale { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
