//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tortuga_Dobrodiy_3isp11_16.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProdTag
    {
        public int IDprod { get; set; }
        public string ProdTitle { get; set; }
        public int IDtag { get; set; }
        public string TagTitle { get; set; }
    }
}
